updated to redocly, edited up the spec
TheMdTF/mdtf-public pull request #79
Opened 2024-06-24 16:50 UTC by rbell13

@johnarleyburns please review and let me know what you think. This should be up to date for the upcoming collection event

2024-06-24 17:36 UTC, rbell13 commented
For more details, see: https://idslabs.atlassian.net/browse/SW-3958

2024-07-02 17:47 UTC, johnarleyburns requested changes
Don't we need to update the API version?

2024-07-08 18:00 UTC, johnarleyburns approved these changes

2024-07-09 18:53 UTC, johnarleyburns approved these changes
Attempting approval

2024-07-11 15:27 UTC, merged